Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -100,43 +100,50 @@ jobs:
         run: |
           # Remove all bottled formulas
           brew uninstall $(brew list)
-
-          # Download taps from deus0ww and homebrew/core
-          brew tap dafyk/mpv
-          brew tap homebrew/core
-          brew cleanup --prune=all
-          brew update-reset
-          echo "next step: install dependencies"
-          brew install curl
-          brew reinstall -s $(brew deps --include-build -n dafyk/mpv/mpv) | :
+          mkdir Bottles
+          cd Bottles
+          brew install -s --build-bottle ../Formulae/pkg-config.rb
+          cd ..
+          git add .
+          git commit -m 'Added pkg-config homebrew bottle'
+          git push
+          exit 1
+          # # Download taps from deus0ww and homebrew/core
+          # brew tap dafyk/mpv
+          # brew tap homebrew/core
+          # brew cleanup --prune=all
+          # brew update-reset
+          # echo "next step: install dependencies"
+          # brew install curl
+          # brew reinstall -s $(brew deps --include-build -n dafyk/mpv/mpv) | :
           
-          # Disable installing formulas from bottles
-          #find $(brew --repository)/Library/Taps -type f -iname *rb -exec sed -i "" '/bottle do/,/end/c\' {} \;
+          # # Disable installing formulas from bottles
+          # #find $(brew --repository)/Library/Taps -type f -iname *rb -exec sed -i "" '/bottle do/,/end/c\' {} \;
           
-          # Force 10.13 deployment target for all homebrew formulas
-          #find $(brew --repository)/Library/Taps -type f -iname *rb -exec sed -i "" $'s/def install/def install\\\n    ENV["MACOSX_DEPLOYMENT_TARGET"] = "10.13"\\\n/' {} \;
-          #for dep in luajit python@3.8 python@3.10; do sed -i "" $'s/MacOS.version/"10.13"/' $(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula//$dep.rb;done
-          #for dep in luajit python@3.8 python@3.10 python@3.11; do find /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula -iname $dep.rb -exec sed -i "" $'s/MacOS.version/"10.13"/' {} +;done
+          # # Force 10.13 deployment target for all homebrew formulas
+          # #find $(brew --repository)/Library/Taps -type f -iname *rb -exec sed -i "" $'s/def install/def install\\\n    ENV["MACOSX_DEPLOYMENT_TARGET"] = "10.13"\\\n/' {} \;
+          # #for dep in luajit python@3.8 python@3.10; do sed -i "" $'s/MacOS.version/"10.13"/' $(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula//$dep.rb;done
+          # #for dep in luajit python@3.8 python@3.10 python@3.11; do find /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula -iname $dep.rb -exec sed -i "" $'s/MacOS.version/"10.13"/' {} +;done
 
-          # Patch formulas for 10.13 deployment
-          #patch -d$(brew --repository)/Library/Taps/deus0ww/homebrew-tap -p1 < mpv-deus0ww-patch.txt
-          #patch -d$(brew --repository)/Library/Taps/homebrew/homebrew-core -p1 < mpv-static-builds-patch.txt
-          #patch -d$(brew --repository)/Library/Taps/deus0ww/homebrew-tap -p0 < ffpmeg.rb.patch
-          #patch -d$(brew --repository)/Library/Taps/deus0ww/homebrew-tap -p0 < mpv.rb.patch
-          #patch -d$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/l -p0 < luajit.rb.patch
-          #patch -d$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/o -p0 < openssl@3.rb.patch
-          #patch -d$(brew --repository)/Library/Taps/deus0ww/homebrew-tap -p0 < libplacebo.rb.patch
-          #patch -d$(brew --repository)/Library/Taps/deus0ww/homebrew-tap -p0 < yt-dlp.rb.patch
-          #patch -d$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/c/ -p0 < cython.rb.patch
-          echo ${{ steps.mpv_tag.outputs.tag }}-${{ github.run_number }}>VERSION
+          # # Patch formulas for 10.13 deployment
+          # #patch -d$(brew --repository)/Library/Taps/deus0ww/homebrew-tap -p1 < mpv-deus0ww-patch.txt
+          # #patch -d$(brew --repository)/Library/Taps/homebrew/homebrew-core -p1 < mpv-static-builds-patch.txt
+          # #patch -d$(brew --repository)/Library/Taps/deus0ww/homebrew-tap -p0 < ffpmeg.rb.patch
+          # #patch -d$(brew --repository)/Library/Taps/deus0ww/homebrew-tap -p0 < mpv.rb.patch
+          # #patch -d$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/l -p0 < luajit.rb.patch
+          # #patch -d$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/o -p0 < openssl@3.rb.patch
+          # #patch -d$(brew --repository)/Library/Taps/deus0ww/homebrew-tap -p0 < libplacebo.rb.patch
+          # #patch -d$(brew --repository)/Library/Taps/deus0ww/homebrew-tap -p0 < yt-dlp.rb.patch
+          # #patch -d$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/c/ -p0 < cython.rb.patch
+          # echo ${{ steps.mpv_tag.outputs.tag }}-${{ github.run_number }}>VERSION
 
-          # Disable all tests in formulas
-          # find $(brew --repository)/Library/Taps -type f -iname *rb -exec sed -i "" '/^  test do/,/^  end/c\' {} \;
+          # # Disable all tests in formulas
+          # # find $(brew --repository)/Library/Taps -type f -iname *rb -exec sed -i "" '/^  test do/,/^  end/c\' {} \;
 
-          #brew reinstall -v -s $(brew deps --include-build -n curl) curl $(brew deps --include-build -n deus0ww/tap/mpv | grep -v -e doxygen -e vulkan-headers -e glslang) deus0ww/tap/mpv || :
-          brew unlink dafyk/mpv/openssl@3 dafyk/mpv/dav1d
-          brew reinstall -v -s dafyk/mpv/mpv
-          echo "mpv build complete"
+          # #brew reinstall -v -s $(brew deps --include-build -n curl) curl $(brew deps --include-build -n deus0ww/tap/mpv | grep -v -e doxygen -e vulkan-headers -e glslang) deus0ww/tap/mpv || :
+          # brew unlink dafyk/mpv/openssl@3 dafyk/mpv/dav1d
+          # brew reinstall -v -s dafyk/mpv/mpv
+          # echo "mpv build complete"
 
       - name: Build Apple Disk Image
         run: |
